language: r
cache: packages
pandoc_version: 1.19.2.1

env:
  global:
    - secure: "RONcybT5tES2XQyTqrjWrNvUYTy34AcXZpxhMEEJY0HxTwJm5fCtcmsTz8EnOGsb/cnaOMKpcrMjk4FbtHgycWm/qV+IeWswPGw1V0YKfvP3e+mmqTRpa0t+BjGLt6DAWo2TyyF6SqlW2YXc6kqd6hgo0+qtOTq56ElkDty5H4iTWLF/8EEcAWe1zWfUp//0oL/aDKV9R1ZG/Jnwu5wCDkl3va3EzQTPV2UYSNiyMorhmFHQ2qC1r4/ycRcdmYD2JZaiczQ0+Evonfgb/VwST9aKQ9HIWctTFX36p5OFtCcvUNQiF3BZ52ne/zWPMElDgYraSbLYclmyVGRfosroV2M7edqPIXSSCvkh+57nINu7Y9u5iikGZpjrtT+IEaLnuiJvnI7+cLC6e86/jt4m/12c7dUyMs4EQrtZVs7jeWl8DWQ8e3UBYieMV9U1qDZ6P9isoojFwqzfqUB+sQ76n9a3RmwRv0Hv96xz5oGnSv1+WfZgRhF/d0ndhpcysaRFFkxQkVeevqz6cTDj0+NNaC6suIAzAq6SKrMQ/W5CWtq55ckemFL4AcYEPjVEI/aEhn2BYZ5ujX+AFabGIB3EGnXHHzq6GzyXiip5vIVU2pcoXJ1KFSWgJHPdmKR0ncxQlxtPWYm1rJlaSBXjd+H1GuNX+r118fMXIy5JVLS/OEI="

script:
  - ./_build.sh
  - ./_deploy.sh
