language: r
cache: packages
pandoc_version: 1.19.2.1

env:
  global:
    - secure: "V9pMr258xzhWLNT+vDCDIgV4tMaM7dCO8BMGGq9dJqxcPkeyxeX8h4kdpOzfmdOHazM3v7RSdG528wkVCD6j9jzMOVSWR/Foe0KqKLe65UPTuWZDMZbeEWUwRAOmGb4rFDV/7zoDgHJqkiRT1vnQWCsFMZkP5W8kIVBwFeOH+38l0PosaHFGf4FweN+MtOKfyhGtiooSQ7YHloe91wOihapfexfvZwEtsG7JcNVGWE6qRQwuGf1QGbg0eXqtvi7pNfRJF6mM1z6IOmeF7IJLgrQK7VqJLRJbiKPa4/tTbT0pwVZ/3+6OnannEgGx0qSrns7jLppcvuy5nXOTQD6uwHGxmB8bbWwGgZ23virDsRM03C4Y/NwKIChsGSsT/igcD58AFZvvaUAf9OmED1u9E7AGIhlbmwtPpjJWZ2MeZQnz/NtWwYNVTIxW10LvX6uQQJnJpK/1y0lONMw4CseRbJNEhAZ/G5vfEadEBopdACPj1Scmeozs2R/oay3XaxNgdcOsg3zNI2XI16Ge2Mwv+DN4GZsZ5nqZpLkLbQV2RvfyDMl3NFPqqyDZ4rh4j+F8D9ijlrJfKX3ZHykaU2IFUmjNxesfwzB3fyO6eJweCmnNXw+sbDnVrqQU51e9t7fqCc4T+zhlN/m97wk4/WaodSGeGe1qEp0hlMisclzjWCQ="

script:
  - ./_build.sh
  - ./_deploy.sh
