language: r
cache: packages
pandoc_version: 1.19.2.1

env:
  global:
    - secure: "t5JG9/feif3BIT1Da5Yi5BgMgzu5NYwMpApKG9wfiKiwK8ihIzGuCRx7Ijb7cU2F88fjkYlkJWzIEEdzUp11MwXq4CwBqw2wbdHoDV43x0jMt2LSgRY9/zhHf6l3t7EpFllecexf1R9FkVEo8Ymzwp8I1EWBPLUHhChjWA1JLuRw9pndNqtq4S6E/EYvfSIqfs2JDoIo2pBnA3rQYfLJtN4KnAGJe/u9koF+tJBoIO9h34UPALf2Ev8URnBWjqq5RCjdwQvffn4p4jPb45OYgQnVsmFtyM9N6+rGJ0L0jttZByownLYWzq5NVeJYC4dWRW0tmd5NB6i2ySS4Up9+iXUfslhnJUCAiy0wZR7sU4mmj+8zS4nVIlTYdhiH7/Bob7A6s06wVzpLby4Lv+oF2TW5ErkLNFr/krJInzofSq5zScNcWj9iLOABA7K+RghvhxARTw7lokB2/oH0kiJwmAMdTtsRZQVPWq+Htt/S2RQBXIKY4+h5J8j6XUieGJ/C1U8iwXhq+bQd9CaHvlpJAZ/5067KeRGi7F17FKRkkWCycImFUeSy2MpAgzPdO4LNpzWmk3aNChrvK1qqwCr38XdUlYbiw46CD9wkudXX5jrcgeXMZjqmG96MMBiZScRwiH0G/TJGcyeKPoba3BD2mdjHg4L5r1saBtFoMY7W29c="

script:
  - ./_build.sh
  - ./_deploy.sh
